services:
  - type: web
    name: ai-sales-forecasting-backend
    env: python
    buildCommand: pip install -r web_app/requirements.txt
    startCommand: gunicorn --chdir web_app app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: ENV
        value: production
