from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.lib import colors
from reportlab.graphics import renderPM
from reportlab.graphics.charts.textlabels import Label
from datetime import datetime

# ----------------------------
# Sample Prediction Value
# ----------------------------
predicted_sales = 51424.24

# ----------------------------
# Create PDF
# ----------------------------
doc = SimpleDocTemplate("Sales_Report.pdf", pagesize=letter)
styles = getSampleStyleSheet()
elements = []

# ----------------------------
# Title
# ----------------------------
title = Paragraph("<b><font size=18>AI Sales Forecasting Report</font></b>", styles['Title'])
elements.append(title)
elements.append(Spacer(1, 20))

# ----------------------------
# Date & Time
# ----------------------------
date = datetime.now().strftime("%d-%m-%Y %H:%M:%S")
elements.append(Paragraph(f"<b>Date:</b> {date}", styles['Normal']))
elements.append(Spacer(1, 10))

# ----------------------------
# Prediction Result
# ----------------------------
elements.append(Paragraph(f"<b>Predicted Sales:</b> ₹ {predicted_sales:.2f}", styles['Normal']))
elements.append(Spacer(1, 20))

# ----------------------------
# Description
# ----------------------------
description = """
This report is automatically generated using the AI Sales Forecasting Dashboard.
The machine learning model predicts future sales based on historical data.
"""
elements.append(Paragraph(description, styles['BodyText']))
elements.append(Spacer(1, 20))

# ----------------------------
# Footer
# ----------------------------
elements.append(Spacer(1, 20))
elements.append(Paragraph("<b>Generated by:</b> AI Sales Forecasting Dashboard", styles['Normal']))

# ----------------------------
# Build PDF
# ----------------------------
doc.build(elements)

print("Report Generated Successfully!")
print("File Name: Sales_Report.pdf")