# pyrefly: ignore [missing-import]
from flask import Blueprint
import os
import sys
import tempfile
import logging
from flask import jsonify, send_file
from datetime import datetime

# Removed sys.path modification to avoid ModuleNotFoundError on Vercel

from _services.config import SECRET_KEY, CORS_ORIGINS
import _services.database as database
from _services.auth_service import require_auth

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(name)s: %(message)s',
    handlers=[logging.StreamHandler()]
)
logger = logging.getLogger(__name__)

history_bp = Blueprint("history", __name__)


@history_bp.route('/api/dataset', methods=['GET'])
@history_bp.route('/dataset', methods=['GET'])
@require_auth
def get_dataset():
    try:
        data = database.get_dataset_rows()
        return jsonify(data)
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@history_bp.route('/api/export/excel', methods=['GET'])
@history_bp.route('/export/excel', methods=['GET'])
@require_auth
def export_excel():
    try:
        from openpyxl import Workbook
        rows = database.view_sales()
        wb = Workbook()
        ws = wb.active
        ws.title = "Sales Report"

        headers = ["ID", "Date", "Product", "Category", "Quantity", "Price", "Total", "Profit"]
        ws.append(headers)

        for r in rows:
            ws.append(r)

        temp_filename = os.path.join(tempfile.gettempdir(), "sales_report.xlsx")
        wb.save(temp_filename)

        response = send_file(
            temp_filename,
            as_attachment=True,
            download_name="Sales_Report.xlsx",
            mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )

        @response.call_on_close
        def remove_temp_file():
            if os.path.exists(temp_filename):
                os.remove(temp_filename)

        return response
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@history_bp.route('/api/export/pdf', methods=['GET'])
@history_bp.route('/export/pdf', methods=['GET'])
@require_auth
def export_pdf():
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from reportlab.lib.styles import getSampleStyleSheet
        
        # Defer import to prevent loading pandas/sklearn globally
        from _services.forecast import predict_sales

        rows = database.view_sales()
        total_sales = sum(float(r[6]) for r in rows)

        try:
            sample_prediction = predict_sales(13)
        except Exception:
            sample_prediction = 51424.24

        temp_filename = os.path.join(tempfile.gettempdir(), "sales_report.pdf")

        doc = SimpleDocTemplate(temp_filename, pagesize=letter)
        styles = getSampleStyleSheet()
        elements = []

        title = Paragraph(
            "<b><font size=18 color='#0B3D91'>AI Sales Forecasting Report</font></b>",
            styles['Title']
        )
        elements.append(title)
        elements.append(Spacer(1, 20))

        date_str = datetime.now().strftime("%d-%m-%Y %H:%M:%S")
        elements.append(Paragraph(f"<b>Generated Date:</b> {date_str}", styles['Normal']))
        elements.append(Spacer(1, 10))

        elements.append(Paragraph(
            f"<b>Total Historical Sales:</b> ₹ {total_sales:.2f}",
            styles['Normal']
        ))
        elements.append(Spacer(1, 10))
        elements.append(Paragraph(
            f"<b>Forecasted Sales (Next Month/13):</b> ₹ {sample_prediction:.2f}",
            styles['Normal']
        ))
        elements.append(Spacer(1, 20))

        description = """
        This PDF report is dynamically generated from the AI Sales Forecasting Dashboard.
        The linear regression machine learning model utilizes historical sales trends
        to output automated sales predictions.
        """
        elements.append(Paragraph(description, styles['BodyText']))
        elements.append(Spacer(1, 30))

        elements.append(Paragraph(
            "<b>Report End. Generated by AI Sales Forecasting Dashboard (Web Version)</b>",
            styles['Normal']
        ))

        doc.build(elements)

        response = send_file(
            temp_filename,
            as_attachment=True,
            download_name="Sales_Report.pdf",
            mimetype="application/pdf"
        )

        @response.call_on_close
        def remove_temp_file():
            if os.path.exists(temp_filename):
                os.remove(temp_filename)

        return response
    except Exception as e:
        return jsonify({'error': str(e)}), 500


